# Site settings
title: Dylan Nikol's Blog
email: 
description: "My thoughts"
baseurl: ""
url: "d-r-n.github.io"
twitter_username: DylanRNikol
github_username:  d-r-n

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge